# Generated by Django 4.0.5 on 2022-06-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_books_page', '0003_alter_bookboardmodel_id_bookboardreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookboardmodel',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
