# Generated by Django 4.0.5 on 2022-06-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_books_page', '0004_alter_bookboardmodel_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookboardmodel',
            options={'verbose_name': 'Book Posting', 'verbose_name_plural': 'Book Posting Group'},
        ),
    ]
