# Generated by Django 4.0.5 on 2022-06-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_books_page', '0005_alter_bookboardmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookboardmodel',
            options={},
        ),
        migrations.AlterField(
            model_name='bookboardmodel',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='BookBoardReply',
        ),
    ]
