# Generated by Django 4.0.5 on 2022-07-02 06:47

import category_books_page.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category_books_page', '0006_alter_bookboardmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookboardmodel',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=category_books_page.models.post_image_path),
        ),
    ]
