# Generated by Django 2.2 on 2022-06-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupform',
            name='id',
        ),
        migrations.AlterField(
            model_name='signupform',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
