# Generated by Django 2.2 on 2022-06-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupform',
            name='id',
        ),
        migrations.AlterField(
            model_name='signupform',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
