# Generated by Django 4.0.5 on 2022-06-18 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_page', '0002_auto_20220612_0233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signupForm',
            new_name='signupModel',
        ),
    ]
