# Generated by Django 2.2 on 2022-06-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_page', '0002_auto_20220611_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupform',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signupform',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
