# Generated by Django 4.0.5 on 2022-06-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_page', '0002_auto_20220612_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='signupModel',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='signupForm',
        ),
    ]
